version: "3.7"
services:
  migrator:
    image: ${IMAGE_NAME}:${VAYAR_VERSION}
    command: python manage.py migrate
    environment:
      - VAYAR_DB_NAME
      - VAYAR_DB_USER
      - VAYAR_DB_PASSWORD
      - VAYAR_DB_ROOT_PASSWORD
      - VAYAR_DB_HOST
      - VAYAR_DB_PORT
    build:
      context: backend/
      args:
        - HTTPS_PROXY
    depends_on:
      database:
        condition: service_healthy
  telegrambot:
    image: ${IMAGE_NAME}:${VAYAR_VERSION}
    command: bash -c "sleep 2 && ./manage.py telegrambot"
    restart: unless-stopped
    environment:
      - VAYAR_SECRET_KEY
      - VAYAR_DB_USER
      - VAYAR_DB_PASSWORD
      - VAYAR_DB_NAME
      - VAYAR_DB_HOST
      - VAYAR_DB_PORT
      - VAYAR_TELEGRAM_BOT_TOKEN
    ports:
      - "9090:9090"
    build:
      context: backend/
      args:
        - HTTPS_PROXY
    depends_on:
      migrator:
        condition: service_completed_successfully
  database:
    image: postgres:14.6-alpine3.17
    environment:
      - POSTGRES_PASSWORD=$VAYAR_DB_ROOT_PASSWORD
      - VAYAR_DB_USER
      - VAYAR_DB_PASSWORD
      - VAYAR_DB_NAME
    ports:
      - $DB_PORT_MAPPING
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $VAYAR_DB_USER -d $VAYAR_DB_NAME" ]
      interval: 1s
      timeout: 2s
      retries: 7
      start_period: 1s
    volumes:
      - ./.db-data/:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
