#!/bin/bash
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${VAYAR_DB_USER} WITH ENCRYPTED PASSWORD '${VAYAR_DB_PASSWORD}';
    CREATE DATABASE ${VAYAR_DB_NAME};
    ALTER USER ${VAYAR_DB_USER} CREATEDB;
EOSQL
