---
name: Master Workflow
on:
  push:
    branches:
      - master
env:
  HELM_MAX_HISTORY: "5"
jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install
        working-directory: ./backend/
      - name: Start database
        run: docker-compose up -d database
      - name: Wait for DB to get ready
        # TODO: Instead of blind sleep, check DB health.
        run: sleep 2
      - name: Run unit tests
        working-directory: ./backend/
        run: pipenv run python -W error::RuntimeWarning ./manage.py test
  check-migrations:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install
        working-directory: ./backend/
      - run: pipenv run python ./manage.py makemigrations --dry-run --check
        working-directory: ./backend/
  build-backend-image:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: registry.hamdocker.ir/emranbm/vayar
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v4
      - name: darkube-cli build & push
        run: 'darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME}
        --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG}} --workdir . --file ./backend/Dockerfile
        --build-context ./backend/ '
  deploy:
    runs-on: ubuntu-20.04
    needs:
      - build-backend-image
      - unit-tests
      - check-migrations
    container: hamravesh/darkube-cli:v1.1
    steps:
      - name: darkube-cli deploy
        run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_VAYAR_EMRANBM_VAYAR_HAMRAVESH_C14}}
          --app-id ${{secrets.APP_ID_VAYAR_EMRANBM_VAYAR_HAMRAVESH_C14}} --image-tag
          ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}